"use client";
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppContext } from "./context/AppContext";
import { useState } from "react";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [callParentFunction, setCallParentFunction] = useState(false);
  const [board, setBoard] = useState<Board>(
    Array(3)
      .fill(null)
      .map(() => Array(3).fill(null))
  );
  const [x, setX] = useState<number | null>(null);
  const [y, setY] = useState<number | null>(null);
  const handleClick = (
    callParentFunction: boolean,
    x?: number | null,
    y?: number | null
  ) => {
    console.log("handleClick", callParentFunction, x, y);
    setCallParentFunction(callParentFunction);

    setX(x ?? null); // Fallback to null if x is undefined
    setY(y ?? null); // Fallback to null if y is undefined
  };

  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppContext.Provider
          value={{ handleClick, board, callParentFunction, setBoard, x, y }}
        >
          {children}
        </AppContext.Provider>
      </body>
    </html>
  );
}
